Import("env")

def source(file):
    return "#/src/demo/" + file


env["source_files"] += [
    source("game.cpp")
]


SConscript("#/src/demo/triangle/SConscript", exports="env")
SConscript("#/src/demo/color_triangle/SConscript", exports="env")
SConscript("#/src/demo/index_buffer/SConscript", exports="env")